### ISSUE TITLE
ng-block-ui gets stuck and never stops loading/blocking

### ISSUE THREAD

**Issue by mbaric1** [kuuurt13/ng-block-ui#124]
Hi
Found an issue where ng-block-ui gets stuck. Happens when I am changing tabs on the view.

1. First tab, gets the data from http and stops loading
2. Change to second tab, gets data from http and stop loading
3. Back to the first tab, gets data, loading and never stops

Also noticed that sometimes loading is applied to wrong elements.

I'll be able to create stackblitz soon.

```
Angular: 9.0.5
ng-block-ui: 3.0.0-beta.6
```

Thanks!

**Comment by mbaric1** [comment]
@kuuurt13 
Providing simple repo https://stackblitz.com/edit/angular-789rd3
To reproduce bug quickly navigate between these tab1 and tab2, when you return to tab1 loading will be stuck. I am not sure, but seems that NgBlockUI Instance is not destroyed with component.

**Comment by kuuurt13** [comment]
@mbaric1 thank you so much for creating a stackblitz for your issue, I really appreciate it! 

I took a look at your example and one thing that you can currently do to fix your issue is to call `this.blockUIList.reset()` instead of `this.blockUIList.stop()`. By calling reset it will clear blocking regardless of how many times start was called.

With that being said you are 100% correct, I don't think that the directive is cleaning up when it is destroyed which might be a good idea to do. Let me look into this a little bit and I should be able to have an update for you soon.

**Comment by mbaric1** [comment]
No problem, thanks for quick response.

Wanted to mention that same thing is happening when using service, might be good idea to clean up service instance as well as directive.

**Comment by kuuurt13** [comment]
@mbaric1 I have added the fix and rolled out `3.0.0-beta.7`. I have forked your stackblitz and updated to use the latest beta and it looks like it fixes the issue. Feel free to test it out and let me know if everything is working for you.
https://stackblitz.com/edit/angular-1ep8kb?embed=1&file=src/app/tab1/tab1.component.ts

**Comment by mbaric1** [comment]
Thanks a lot. Can confirm that it is working now.
