### ISSUE TITLE
Creating one service for all registration and blocking

### ISSUE THREAD

**Issue by KJcBahia** [kuuurt13/ng-block-ui#18]
Hi. I would also like to know how to implement this. If I have a lot of components to block, I would declare it in every component I would like to use it (eg: @BlockUI('block') block: NgBlockUI;) I want to create a service that would do the registration for me and that also controls the start and end of the blocking based on the name I gave it. From what I've read, decorators are only declared class level and not in method levels. Thanks :D

**Comment by kuuurt13** [comment]
@KJcBahia so I think I am following you. You want to block multiple components at once and you are looking to abstract starting/stopping blocking methods out into a service. That service can then be passed a `NgBlockUI` instance name and it can be used to start/stop blocking for all those components with a single method call? Let me know if that sounds right, if that is the case then that should be possible and I can create a plunker outlining how to achieve that.

**Comment by fatespinosa** [comment]
Hi @kuuurt13, I think what he was saying was instead of importing the BlockUI and NgBlockUI in all of components that will use it, why not just create a service that registers an instance and at the same time, the service can be called to start and stop the blocker.

Something like this

void registerInstance(instanceName: string){
if(!container[instanceName]){ // container is the list of BlockUIs, checks if not yet existing
// register it
}

void startBlocking(instanceName: string){
container[instanceName].start();
}

void endBlocking(instanceName: string){
container[instanceName].stop();
}

This way, it can be done by just importing the service and registration is not just during class declaration (maybe at some point in time like ngOnChanges or so) since decorators aren't supposed to be declared in methods. Finally, when the component is destroyed, something like this can be done.

in the component:
ngOnDestroy(){
this.blockUIService.unRegisterInstance("sample");
}

in the service:
void unRegisterInstance(instanceName: string){
if(container[instanceName]){ // checks if existing
// destroy it
}

**Comment by kuuurt13** [comment]
@fatespinosa I see what you are saying now. The service the decorator currently uses behind the scenes does something similar to this except with observables. The decorator is just syntactic sugar used to wire a variable up to specific instances so you don't have to specify the instance name each time you want to start and stop blocking. I can see the value in exposing a service that would allow you to pass a specific instance name though. Basically I just need to make some tweaks to the current service and exposes it publicly within the library. I will see if I can knock out a prototype this week and I will make sure to keep you and @KJcBahia in the loop.

**Comment by KJcBahia** [comment]
@kuuurt13  Thanks kurt. That is what i am trying to say. Looking forward to this :+1:

**Comment by fatespinosa** [comment]
@kuuurt13 Thanks a lot! I'll make sure to recommend this one to my co-developers after the update :)

**Comment by kuuurt13** [comment]
@KJcBahia @fatespinosa I just finished a prototype for the new service. Below is a quick outline of the service and here is a [plunker](https://embed.plnkr.co/z41cgz/?show=app.component.ts,preview) that is pointed to a branch that has the new service. 

The service allows you to pass an instance name to the start/stop methods to target specific instances. I also added the ability to pass an array of names to easily block instances in unison if desired. I didn't include the register method which was suggested in an above comment because all instance get registered `onInit` for all BlockUI components and directives. The instances then unsubscribe themselves `onDestroy` of the component or element. In case someone wants to unsubscribe an instance prematurely for any reason I added a method to allow for that as well. Hope this covers the limitations you two were seeing with just using the decorator. Let me know what you two think.

```ts
class BlockUIService {
  /**
  * Starts blocking for given BlockUI instance or instances
  */
  start(target: string | string[], message?: string): void

  /**
  * Stops blocking for given BlockUI instance or instances
  */
  stop(target: string | string[]): void

  /**
  * Unsubscribes for given BlockUI instance or instances
  */
  unsubscribe(target: string | string[]): void 
}
```

**Comment by fatespinosa** [comment]
@kuuurt13 this is perfect! Exactly what I am looking for! Kudos for your effort and openness for this improvement :) 👍

**Comment by kuuurt13** [comment]
@fatespinosa no problem! I will wait to hear back from @KJcBahia and if all is good then I will merge my changes in.

**Comment by KJcBahia** [comment]
Good day @kuuurt13. This is great. Thanks for your time and effort. :+1: Looking forward applying this to our project. Thanks :)

**Comment by kuuurt13** [comment]
@KJcBahia great. I will get this merged in when I get out of work tonight and I will publish a new version to npm.

**Comment by kuuurt13** [comment]
@KJcBahia @fatespinosa #19 has been merged and I released a new version to npm with the changes. I am now closing this issue. Thanks again for the input and I hope this will be a useful feature for you two and everyone else.

**Comment by KJcBahia** [comment]
I will try it now. Thanks again kurt. :+1:

**Comment by AlwaysAbhl001** [comment]
can any one post working stackblitz here ?

**Comment by kuuurt13** [comment]
@AlwaysAbhl001, here is a [plunker](https://plnkr.co/edit/z41cgz?p=preview) that was created a while ago that has an example.
