### ISSUE TITLE
Warning Template parse warnings

### ISSUE THREAD

**Issue by EduardoSouzaDF** [kuuurt13/ng-block-ui#26]
First, thanks for ng-blobk-ui, it's very simple, cool and useful, but  its have warnings in console:

im using:
@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5

the warning is:
The <template> element is deprecated. Use <ng-template> instead ("
    </div>
  </div>
  [WARNING ->]<template *ngIf="templateCmp" #templateOutlet></template>
</div>
"): ng:///BlockUIModule/BlockUIContentComponent.html@8:2

How fix it? 

Thanks

**Comment by kuuurt13** [comment]
Hey @EduardoSouzaDF, glad to hear you like the library. I think this issue has to do with using `template` instead of `ng-template`. I checked the latest [code](https://github.com/kuuurt13/ng-block-ui/blob/1.0.0-beta/lib/components/block-ui-content/block-ui-content.component.template.ts#L9) and the npm package and it looks like if you are using `1.0.0-beta.10` then you shouldn't be seeing the issue.

To allow me to better help you, can you give me more info on how you are using the library. Like are you trying to use a custom template or anything in particular? Also can you run `npm list ng-block-ui` in you project and let me know what is returned. Thanks!

**Comment by kuuurt13** [comment]
Hey @EduardoSouzaDF, any update on this? Just wanted to know if you figured your issue out so I can close this. Thanks.

**Comment by kuuurt13** [comment]
Closing for now since it has been a few weeks. If you still have the issue re-open this or create a new ticket. Thanks.
