### ISSUE TITLE
angular 4 compatibility

### ISSUE THREAD

**Issue by nerumo** [kuuurt13/ng-block-ui#34]
I you build with ng 4 and AOT enabled, you get this warning.

```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
    </div>
  </div>
  [WARNING ->]<template *ngIf="templateCmp" #templateOutlet></template>
</div>
```
would be nice to upgrade this lib to ng 4 to avoid this warning. tnx

**Comment by kuuurt13** [comment]
@nerumo this library is already compatible with ng 4. Please see https://github.com/kuuurt13/ng-block-ui#installation. The versions are split currently because ng 4 has a different way of doing AOT compiling so I need to have 2 version to stay compatible with both ng 2 and 4. When ng 5 comes out I plan on moving this library to `1.0.0` and dropping support for 2. Ng 5 AOT compiling should be backwards compatible with ng 4 so I will no longer need to split out my npm package.

**Comment by nerumo** [comment]
@kuuurt13 sorry, I missed that. tnx
