### ISSUE TITLE
BlockUI animation on hide

### ISSUE THREAD

**Issue by s13571** [kuuurt13/ng-block-ui#64]
Hey, I'm using your library with my custom template and I'm struggling with one thing. I tried using built in angular animations as well as css. So animation for showing block content is working fine with both techniques, but hiding is something I cannot do with any of these. Do you have any idea how could I do sooth fadeOut animation for istance? I'm using blockUI as directive and start it with start() and stop() methods in components. But I need some general animation to show and hide blocker. I would be great if you could help me with that.

**Comment by kuuurt13** [comment]
Hey, without seeing some code I can't help too much with your specific issue you are seeing. I do know that it is possible to create a fade in/out transition using CSS. Checkout out this sample code I created for more details https://codesandbox.io/s/ov07l3rz69?module=%2Fsrc%2Fstyles.css. 

What you have to do is overwrite the default styles that the library applies. It uses `display: block/none` to toggle visibility. So that can hide the element before your animations/transitions are finished. Take a look at the code I shared and let me know if that works for you.

**Comment by s13571** [comment]
Ok I was missing z-index property... Thank you a lot, great lib!

**Comment by kuuurt13** [comment]
Thanks, no problem! Going to close this issue then.
