### ISSUE TITLE
BlockUIHttpModule not working for multiple requests

### ISSUE THREAD

**Issue by mackski** [kuuurt13/ng-block-ui#67]
The BlockUIHttpModule only seems to block a single current request. If I have multiple concurrent requests, only the first one is blocked, anything there after is ignored.

Is this a bug or by design?
Is there a possibility of adding an option to block until all requests are completed?

**Comment by kuuurt13** [comment]
This is related to #43. Currently by default the library doesn't queue calls to block `stop`/`start`. That means that if you call `start` twice but later call `stop` once it will stop the blocking. For the next major release I plan on changing this behavior so that if block `start` is called twice then block `stop` would need to be called twice to stop blocking (or call `reset` at anytime to clear all `start` calls). This would fix this issue that you are seeing and make it easier to handle multiple concurrent requests.

**Comment by bhaskarmishra** [comment]
@kuuurt13 When do you plan to release this? or could you do a beta with this fix?

**Comment by kuuurt13** [comment]
@bhaskarmishra this already is in 2.0.0-beta.2, see the [changelog](https://github.com/kuuurt13/ng-block-ui/blob/beta/CHANGELOG.md#new-features).  I plan on releasing `2.0.0` soon now that Angular 7 is out. I like to target the newest release of Angular as a `beta` release in case there are any breaking changes/compatibility issue (like what happened with Angular 6 and RxJS 6)

**Comment by amitagrawal11** [comment]
I had already installed version 2.0.0-beta.3 but still getting same issues i.e. while making multiple api calls it does not block ui. Instead, it works for one request whenever it gets response it stops the blockui and does not wait for other request to complete.

May I need to do anything else to achieve ?

**Comment by kuuurt13** [comment]
@amitagrawal11 I can't seem to reproduce your issue, see this [example](https://codesandbox.io/s/korn5vy8xo). If you can send me an example that reproduces the issue you are seeing I can look into it for you
