### ISSUE TITLE
Not able to import.

### ISSUE THREAD

**Issue by akash-potdar7** [kuuurt13/ng-block-ui#68]
Compilation error on importing: cannot find ng-block-ui
These are my app rxjs and ng versions.
"rxjs": "^5.5.10"
"ng": "^5.2.0"

**Comment by kuuurt13** [comment]
What do you get when you run `npm list ng-block-ui`?

**Comment by akash-potdar7** [comment]
I get this from **npm list ng-block-ui**
-- ng-block-ui@1.0.4

package.json has **"ng-block-ui": "^1.0.4"** in dependencies.

But when I try to import i in my app.module.ts 
import { BlockUIModule } from 'ng-block-ui';

I see the error: can't find 'ng-block-ui' in node_modules.
ERROR in src/app/app.module.ts(52,31): error TS2307: Cannot find module 'ng-block-ui'.

Hope this is conclusive.

**Comment by kuuurt13** [comment]
How did you create your project? Did you use angular CLI or is it something custom?  I am just wondering because this seems like it is an issue with your build step. If you can give me more info on that I can help

Also you can try a few things below:

1) Can you uninstall and install the library `npm uninstall ng-block-ui && npm install ng-block-ui --save   ` . There might have been an issue when installing
2) You can use this https://github.com/kuuurt13/ng-block-ui-example as an reference to see if you're doing something a little different (it was created with angular cli and uses Angular 5.2.0). 
3) You can try cloning and running the above repo to make sure it isn't something specific with your machine

**Comment by akash-potdar7** [comment]
Yes my app is built with using angular-cli.
I have tried uninstalling, it didn't work.
Will try out the other two oprions and let you know.
Thanks.

**Comment by kuuurt13** [comment]
Any luck with this?

**Comment by kuuurt13** [comment]
Closing, feel free to open if you are still having issues.
